### ISSUE TITLE
[dscrutils] set seed

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#104]
The code below:

```yaml
# Simulate samples from the normal distribution with mean 0 and
# standard deviation 1.
normal: R(x <- rnorm(n,mean = mu,sd = 1))
  mu: R(stats::rnorm(1))
  n: 100
  $data: x
  $true_mean: mu

# Simulate samples from the non-centered t-distribution with 3 degrees
# of freedom.
t: R(x <- mu + rt(n,df = 2))
  mu: R(stats::rnorm(1))
  n: 100
  $data: x
  $true_mean: mu
```

Results in 

```
> dscquery("first_investigation",targets="simulate.mu")
  DSC simulate simulate.mu
1   1   normal     -1.4318
2   2   normal     -1.4318
3   1        t      0.5664
4   2        t      0.5664
```

But we want `simulate.mu` be the same since they are parameters. That is, we should set a seed to `dscrutils` -- @pcarbo does it make sense?

BTW @pcarbo if we want `mu` be different for every replicate, the only way to achieve it is to use `raw()` instead of `R()`

**Comment by stephens999** [comment]
maybe we should instead encourage that the script should generate mu and
pass it down as a pipeline variable
and then the user can subset pipelines on this variable rather than
treating it as a parameter?

A related issue is that I do not myself understand exactly what R() does in
the .dsc file, but
it seems based on the above that we should avoid using it to produce random
numbers?

Matthew

**Comment by gaow** [comment]
> maybe we should instead encourage that ... it seems based on the above that we should avoid using it to produce random numbers?

Indeed. We can provide some guideline, or deem this ticket "bad practice"; but there is no way to restrict it from happening, and when it does happen, we want to have some justifiable and consistent behavior, as opposed to confusing people with the discrepancies shown above.

>  I do not myself understand exactly what R() does in

It is just a shortcut to set some parameters, eg, `g: R(1:50)` instead of having to write `g: 1,2,3...`. So what is important to note is that once set, it should be a "parameter", that is, the outcome should be consistent between different module instances, as if one has explicitly written it out in the DSC configuration.  I think this is what justifies `dscrutils` to use a seed.

**Comment by pcarbo** [comment]
@stephens999 My goal here was to test the behaviour of DSC, not to demonstrate Good Practice for using DSC.

My question is this: 

When multiple R scripts are evaluated within the same module, do we want the code to be evaluated using the same seed, or different seeds?

Additionally, if I define this module:

```yaml
normal: R(x <- rnorm(n,mean = mu,sd = 1))
  seed: R(1:10)
  mu: R(stats::rnorm(1))
  n: 100
  $data: x
  $true_mean: mu
```

does `seed` change the result for both R scripts in the module?

Although I do understand the points made above, personally I prefer simpler behaviour, and to me the simpler behaviour is to have all R scripts within a module share the same seed. Conceptually, it is difficult to keep track of multiple seeds within the same module.
