### ISSUE TITLE
Module parameters (and module outputs?) with named lists and vectors

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc#111]
I can see this being useful in many cases (but not essential).

For example, currently I have module definition

```yaml
t: R(mu <- par[[1]]; df <- par[[2]]; x <- mu + rt(n,df))
  par: R(c(mu = 0,df = 2)),
       R(c(mu = 1,df = 2)),
       R(c(mu = 2,df = 4))
  n: 100
  $data: x
  $true_mean: 3
```

But it would be nice to have:

```yaml
t: R(x <- par$mu + rt(n,par$df))
  par: R(c(mu = 0,df = 2)),
       R(c(mu = 1,df = 2)),
       R(c(mu = 2,df = 4))
  n: 100
  $data: x
  $true_mean: 3
```

DSC removes the names of the vector/list elements.

Again, not essential, but something to consider.
