### ISSUE TITLE
ERROR: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc#146]
My DSC block was:

```yaml
DSC:
    define: mean: unbiased_mean, huber_mean
    run: simulate * mean * sq_error
```

When running `dsc example.dsc`, I got this error:

```
ERROR: 'list' object has no attribute 'items'
```

It was an error in the syntax of the `define` statement; it would be good to have a more informative error message.
