### ISSUE TITLE
Generating parameters with `Python{...}`?

### ISSUE THREAD

**Issue by ivirshup** [stephenslab/dsc#152]
From the [documentation](https://stephenslab.github.io/dsc-wiki/reference/DSC_Configuration.html#Language-interpreters-132), my understanding was that I could generate variables with R, Python, or Shell expressions. However, I'm having some trouble getting this to work with Python. Here's a quick example:

```yaml
generate: header.py + Python(np.random.seed(i); sample = np.random.random_sample(100))
  i: Python(list(range(10)))
  $data: sample
```

This returns an error, saying lists are unhashable. If I use `i: Python{tuple(range(10))}`, I only get one output. This seems to work fine with either `i: R{c(1:10)}` or `i: Shell{echo {1..10}}`.

Is there a way to define variables with Python statements?

**Comment by gaow** [comment]
@ivirshup thanks for the bug report. It has been fixed in `master` branch and in our current release. Would you please run:

```
pip install -U --upgrade-strategy only-if-needed dsc
```

and try it again? You should be on 

```
$ dsc --version
0.3.0
```

after the upgrade. 

>  If I use i: Python{tuple(range(10))}, I only get one output. 

Yes, and I think you see that it is expected behavior.

**Comment by ivirshup** [comment]
Sorry about the late response! It's working as expected now, thanks!

One follow up question, should something like: `Python{import numpy as np; np.linspace(0.4, 2, 17)}` be allowed?

**Comment by gaow** [comment]
> Sorry about the late response! It's working as expected now, thanks!

Thank you @ivirshup good to know!

> One follow up question, should something like: Python{import numpy as np; np.linspace(0.4, 2, 17)} be allowed?

It should work -- does it?

**Comment by ivirshup** [comment]
With the file `example.dsc`:

```yaml
step: Python(x=y)
  y: Python{import numpy as np; np.linspace(0.4, 2, 17)}
  $x: x

DSC:
  define:
    simulate: step
  run: simulate
  output: example
```

Run with `dsc example.dsc` I get the error:

```python
ERROR: Evaluation of the following Python expression failed:
import numpy as np; np.linspace(0.4, 2, 17).
Error message: invalid syntax (<string>, line 1)
```
