### ISSUE TITLE
Not all groups are parsed in DSC file.

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc#173]
Example:

```yaml
DSC:
  define:
    simulate: toydata
    fit:      ridge, lasso, elastict_net
    predict:  predict_ridge, predict_lasso, predict_elastic_net
    analyze:  ridge * predict_ridge,
              lasso * predict_lasso,
              elastic_net * predict_elastic_net
    score:    mse
  run: simulate * analyze * score
```

The DSC ran even though there is a typo above---`elastict_net` should be `elastic_net`. It would be good to identify these errors early on.
