### ISSUE TITLE
Output x is defined in module a but not in module b; error reported by dscquery

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/dsc#202]
Here's an example illustrating the problem.

This is `test.dsc`:

```yaml
DSC:
  define:
    fit: ridge, elastic_net
  run: fit

ridge: R(beta <- 2)
  lambda_est_method: "lambda.min", "lambda.1se"
  $beta:             beta

elastic_net: R(alpha <- 1; beta <- 1)
  $alpha:    alpha
  $beta:     beta
```

This is `test.R`:

```R
library(dscrutils)
# This works.
out1 <- dscquery("test","fit.beta")
# This does not.
out2 <- dscquery("test",c("fit.alpha","fit.beta"))
```

The second dscquery command returns the following error:

```
ERROR: Cannot find variable alpha in module ridge
```
