### ISSUE TITLE
Combinations of parameters syntax

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#213]
I'm looking at my DSC for M&M: 

```
mnm_base: mnm.R
  ...
  missing_Y: TRUE, FALSE
  resid_method: 'oracle', 'diag', 'flash'
  ...
```

The problem here is that when `missing_Y` is `TRUE` it does not make sense to run `resid_method: 'oracle'`. Currently this can be implemented in DSC as:

```
mnm_base: mnm.R
  ...
  missing_Y: TRUE, FALSE
  resid_method: 'oracle', 'diag', 'flash'
  @FILTER: not (missing_Y == "TRUE" and resid_method == "'oracle'")
  ...
```

1. Is there a better syntax to achieve it?
2. I'm not sure how to remove the awkward `"` for this to work; unless I work harder at the parser.

**Comment by pcarbo** [comment]
@gaow You could have two modules, e.g.,

```yaml
mnm_full_Y: mnm.R
  ...
  missing_Y: FALSE
  resid_method: 'oracle', 'diag', 'flash'
  ...

mnm_missing: mnm.R
  ...
  missing_Y: TRUE
  resid_method: 'diag', 'flash'
  ...
```

And you could use the module inheritance in some way to make the code more concise.
