### ISSUE TITLE
Interface for using docker / singularity images per module

### ISSUE THREAD

**Issue by gaow** [stephenslab/dsc#214]
We can exploit `@CONF` which is an existing feature; for example:

```
susie: R(...)
  @CONF: container='gaow/susieR', engine='singularity'
```

It is trickier if one has to switch between `docker` and `singularity`. Alternatively we can try:

```
susie: R(...)
  @CONF: container='gaow/susieR', engine=${engine}

DSC:
  global:
     engine: "docker"
```

Then use `dsc script --engine docker` and `dsc script --engine singularity` to switch between them. `--` followed by an unknown argument will be parsed as `DSC::global`.

Or even:

```
susie: R(...)
  @CONF: container='gaow/susieR'

DSC:
  container_engine: "docker"
```

That is, add a parameter `DSC::container_engine` for the purpose. 

At this point I prefer the 3rd proposal with `container_engine`.
