### ISSUE TITLE
Duplicated combination of parameters in parameter group syntax

### ISSUE THREAD

**Issue by minqiao** [stephenslab/dsc#215]
Example:

```yml
test: R()
 (addz, ld_method): (FALSE, "in_sample"), (FALSE, "ref_sample"), (TRUE, "ref_sample")
 $z: 1
```

```
$ dsc test.dsc --target test

Failed to process step output (data_io['output']): Output test/test/test_1.rds from substep 0 of 1 substeps overlaps with output from a previous substep.
[DSC]: Exits with 1 pending step (output validation)

```

This is because when taking combinations of `add_z` and `ld_method`, DSC does the following:

```
addz = [F,F,T]
ld_method = [I, R, R]
combo = [(x,y) for x, y in zip(add_z, ld_method) if (x==F and y == I) or (x == F and Y == R) or (x == T and Y==R)]
```

but it failed to take into consideration that `add_z` and `ld_method` constructed this way already are non-unique lists. It should take the values in these lists to start with, when parameter group syntax is involved.
